// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdhcWgzcl2XwHQxKPfYcU83JPHI74ClGk',
    appId: '1:176702486429:web:3f68665aae5ed1dc63e174',
    messagingSenderId: '176702486429',
    projectId: 'official-twitter-ki967',
    authDomain: 'official-twitter-ki967.firebaseapp.com',
    storageBucket: 'official-twitter-ki967.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSTncLty098AEZrB3R3k4j5w1xPvkCOOE',
    appId: '1:176702486429:android:ea311edad120565663e174',
    messagingSenderId: '176702486429',
    projectId: 'official-twitter-ki967',
    storageBucket: 'official-twitter-ki967.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKMdE84xQJ7AD4p0yuTvh2-2HXulA3WSg',
    appId: '1:176702486429:ios:4e7f72de828f7ab463e174',
    messagingSenderId: '176702486429',
    projectId: 'official-twitter-ki967',
    storageBucket: 'official-twitter-ki967.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKMdE84xQJ7AD4p0yuTvh2-2HXulA3WSg',
    appId: '1:176702486429:ios:e1ed0ccd27489cd363e174',
    messagingSenderId: '176702486429',
    projectId: 'official-twitter-ki967',
    storageBucket: 'official-twitter-ki967.appspot.com',
    iosBundleId: 'com.example.twitterClone.RunnerTests',
  );
}
